title:              Yewon's Blog
email:              rac8793@naver.com
description:        I am a computer engineering student who is interested in web development.
author:             Yewon Shin
url:                "https://shinyewon.github.io"

# Social Profiles
github_username:    shinyewon
facebook_username:  신예원
instagram_username:  yewon77
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
